Add condition to check upload state

diff --git a/pipelines/ci.yml b/pipelines/ci.yml
--- a/pipelines/ci.yml
+++ b/pipelines/ci.yml
@@ -59,13 +59,21 @@ stages:
         echo "Obtaining an access token..."
         ACCESS_TOKEN=$(curl "https://accounts.google.com/o/oauth2/token" -d "client_id=${CLIENT_ID}&client_secret=${CLIENT_SECRET}&code=${CODE}&grant_type=authorization_code&redirect_uri=urn:ietf:wg:oauth:2.0:oob" | jq -r .access_token)
         echo "Uploading $(build.artifactStagingDirectory)/$(build.buildNumber).chrome.zip..."
-        curl -H "Authorization: Bearer ${ACCESS_TOKEN}" -H "x-goog-api-version: 2" -X PUT -T "$(build.artifactStagingDirectory)/$(build.buildNumber).chrome.zip" -v "https://www.googleapis.com/upload/chromewebstore/v1.1/items/${APP_ID}"
-        echo "Publishing to trusted testers..."
-        curl -H "Authorization: Bearer ${ACCESS_TOKEN}" -H "x-goog-api-version: 2" -H "Content-Length: 0" -H "publishTarget: trustedTesters" -X POST -v "https://www.googleapis.com/chromewebstore/v1.1/items/${APP_ID}/publish"
+        UPLOAD_RESPONSE=$(curl -H "Authorization: Bearer ${ACCESS_TOKEN}" -H "x-goog-api-version: 2" -X PUT -T "$(build.artifactStagingDirectory)/$(build.buildNumber).chrome.zip" -v "https://www.googleapis.com/upload/chromewebstore/v1.1/items/${APP_ID}")
+        UPLOAD_STATE=$(echo ${UPLOAD_RESPONSE} | jq -r .uploadState)
+        if [ ${UPLOAD_STATE} != "FAILURE" ];
+        then
+          echo "Publishing to trusted testers..."
+          curl -H "Authorization: Bearer ${ACCESS_TOKEN}" -H "x-goog-api-version: 2" -H "Content-Length: 0" -H "publishTarget: trustedTesters" -X POST -v "https://www.googleapis.com/chromewebstore/v1.1/items/${APP_ID}/publish"
+        else
+          echo "Extension upload failed with response ${UPLOAD_RESPONSE}"
+          exit 1
+        fi
       env:
         APP_ID: $(Chrome.WebStore.ExtensionId)
         CLIENT_ID: $(Chrome.WebStore.ClientId)
         CLIENT_SECRET: $(Chrome.WebStore.ClientSecret)
         CODE: $(Chrome.WebStore.Code)
+      displayName: 'Publish to Chrome web store'
 
 # TODO: Add parallel draft release stages for firefox and edge (?)
